import type { Metadata } from "next";
import { Barlow, Geist } from "next/font/google";
import { Lato } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/shared/nav/Navbar";
import Footer from "@/components/shared/footer/footer";



// Lato font
const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});
// Barlow font
const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`  ${lato.variable} ${barlow.variable} antialiased container mx-auto px-4`}
      >
        <Navbar />
        <div className="border-l border-r border-sidebar ">

        {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
